# -*- coding: utf-8 -*-
"""Copy of SRI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQpXppHW4ANZNf9FQccT5KTK6jMILGWm

# Cement Industry Carbon Emission Analysis

## Project Overview

This notebook is designed for exploratory data analysis (EDA) and carbon emission estimation specifically within the cement industry. The cement industry is a significant contributor to global CO₂ emissions, accounting for approximately 7–8%.

### Objectives:
- **Data Acquisition**: Fetch or scrape relevant public datasets and statistics from online sources.
- **Data Preprocessing**: Clean and prepare the data for analysis.
- **Exploratory Data Analysis (EDA)**: Understand data distribution, relationships, patterns, and anomalies.
- **Carbon Emission Calculation**: Implement a modular Python class to calculate emissions based on activity data and emission factors.
- **Visualization**: Create various plots (pie charts, bar graphs, trend plots) to visualize emission sources, energy consumption, and overall sustainability insights.
- **Modularity & Scalability**: Develop a professional, research-oriented notebook architecture.

### Key Industry Context & Formulas:
- Average emission intensity: 0.54–0.55 tonnes CO₂ per tonne of cement.
- Emission sources: 60–70% calcination, 30–40% fuel combustion.
- Thermal energy intensity: 3.5 GJ per tonne of clinker.
- Electrical intensity: 91 kWh per tonne of cement.
- Clinker ratio: 0.71–0.72.
- **Total Emissions = Activity Data × Emission Factor**
- **Cement Calcination Chemistry**: CaCO₃ → CaO + CO₂

## 1. Setup and Library Imports

This section imports all necessary Python libraries for data manipulation, analysis, and visualization.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests

# Optional: Configure Matplotlib for better aesthetics
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_theme(style="whitegrid")

print("Libraries loaded successfully.")

"""## 2. Data Acquisition

This section focuses on automatically fetching relevant public datasets and statistics from online sources. We will prioritize direct downloads from official websites or APIs. If structured datasets are not directly available, we will explore options for scraping or generating synthetic data based on established benchmarks.

### 2.1. Our World in Data - CO₂ and Greenhouse Gas Emissions

'Our World in Data' provides comprehensive datasets on CO₂ and greenhouse gas emissions, often available as direct CSV downloads. This is a highly relevant source for our project.
"""

# Direct URL to Our World in Data CO₂ and Greenhouse Gas Emissions dataset (usually a CSV file)
# This URL might need to be updated if the source changes it.
# As of my last update, a common URL is:
data_url_owid = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

try:
    df_owid = pd.read_csv(data_url_owid)
    print("Our World in Data CO₂ emissions data fetched successfully.")
    print(df_owid.head())
    print(f"Shape of OWID data: {df_owid.shape}")
except Exception as e:
    print(f"Could not fetch Our World in Data. Error: {e}")
    df_owid = pd.DataFrame()

"""### 2.3. Initial Data Inspection and Cleaning for OWID Data

Now that we have successfully loaded the 'Our World in Data' dataset, we need to inspect its structure, check for missing values, and prepare it for analysis, focusing on the `cement_co2` column.
"""

# Display basic info about the DataFrame
print("\n--- OWID Data Info ---")
df_owid.info()

# Check for missing values in key columns
print("\n--- Missing Values in Key Columns ---")
key_columns = ['country', 'year', 'cement_co2', 'population', 'gdp']
for col in key_columns:
    if col in df_owid.columns:
        print(f"Missing values in '{col}': {df_owid[col].isnull().sum()} ({(df_owid[col].isnull().sum() / len(df_owid)) * 100:.2f}%)")
    else:
        print(f"Column '{col}' not found in DataFrame.")

# Filter out rows where 'cement_co2' is NaN or 0, as these are not useful for emission analysis
df_cement_emissions = df_owid[df_owid['cement_co2'].notna() & (df_owid['cement_co2'] > 0)].copy()

# Focus on relevant columns for cement emissions
df_cement_emissions = df_cement_emissions[['country', 'year', 'cement_co2', 'population', 'gdp', 'iso_code']].copy()

print("\n--- Filtered Cement Emissions Data (first 5 rows) ---")
print(df_cement_emissions.head())
print(f"Shape of filtered cement emissions data: {df_cement_emissions.shape}")

# Further cleaning: Ensure 'year' is integer and 'cement_co2' is numeric
df_cement_emissions['year'] = pd.to_numeric(df_cement_emissions['year'], errors='coerce').astype(int)
df_cement_emissions['cement_co2'] = pd.to_numeric(df_cement_emissions['cement_co2'], errors='coerce')

print("\n--- Data types after cleaning ---")
print(df_cement_emissions.dtypes)

# For future steps, we might need to handle countries with sparse data or aggregate at regional/global levels.

"""## 3. Exploratory Data Analysis (EDA)

This section will perform exploratory data analysis on the `df_cement_emissions` dataset. We will visualize trends, distributions, and relationships to gain insights into cement-related CO₂ emissions globally and by country.

### 3.1. Global Cement CO₂ Emissions Trend

Let's start by visualizing the global trend of cement CO₂ emissions over time.
"""

# Calculate global cement CO2 emissions per year
global_cement_co2 = df_cement_emissions.groupby('year')['cement_co2'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=global_cement_co2, x='year', y='cement_co2', marker='o')
plt.title('Global Cement CO₂ Emissions Over Time')
plt.xlabel('Year')
plt.ylabel('Cement CO₂ Emissions (million tonnes)')
plt.grid(True)
plt.show()

print("Global cement CO₂ emissions data for visualization (first 5 rows):")
print(global_cement_co2.head())

"""### 3.2. Top Countries by Cement CO₂ Emissions

Let's identify the countries with the highest cumulative cement CO₂ emissions and visualize their contributions.
"""

# Filter out aggregate entities from the 'country' column to focus on individual countries
# Common aggregate names include 'World', continents, income groups, etc.
# This list can be expanded based on further inspection of unique country names in df_owid.
aggregate_entities = [
    'World', 'Asia', 'Europe', 'Africa', 'North America', 'South America', 'Oceania',
    'European Union (27)', 'European Union (28)', 'Upper-middle-income countries',
    'High-income countries', 'Lower-middle-income countries', 'Low-income countries',
    'High income', 'Low income', 'Upper middle income', 'Lower middle income',
    'European Union', 'OECD', 'Non-OECD', 'International transport', 'Kuwaiti Oil Fires',
    # Additional regional aggregates identified from previous output:
    'Asia (excl. China and India)', 'Europe (excl. EU-27)', 'Europe (excl. EU-28)', 'North America (excl. USA)',
    'Africa (excl. South Africa)', 'Oceania (excl. Australia and New Zealand)', 'South America (excl. Brazil)' # Further expanded
]
df_countries_only = df_cement_emissions[~df_cement_emissions['country'].isin(aggregate_entities)].copy()

# Calculate cumulative cement CO2 emissions per country from the filtered data
cumulative_country_cement_co2 = df_countries_only.groupby('country')['cement_co2'].sum().reset_index()
cumulative_country_cement_co2 = cumulative_country_cement_co2.sort_values(by='cement_co2', ascending=False)

# Select top N countries (e.g., top 10)
top_n = 10
top_countries_cement_co2 = cumulative_country_cement_co2.head(top_n)

plt.figure(figsize=(14, 7))
sns.barplot(x='country', y='cement_co2', data=top_countries_cement_co2, palette='viridis', hue='country', legend=False)
plt.title(f'Top {top_n} Countries by Cumulative Cement CO₂ Emissions (1880-2024)')
plt.xlabel('Country')
plt.ylabel('Cumulative Cement CO₂ Emissions (million tonnes)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print(f"Top {top_n} individual countries by cumulative cement CO₂ emissions:")
print(top_countries_cement_co2)

"""### 3.3. Annual Cement CO₂ Emissions Trend for Top Countries

Let's visualize the annual cement CO₂ emissions for the top 10 countries to observe their individual trends over time.
"""

# Get the list of top N countries
top_countries_list = top_countries_cement_co2['country'].tolist()

# Filter the main DataFrame to include only these top countries
df_top_countries_trend = df_cement_emissions[df_cement_emissions['country'].isin(top_countries_list)].copy()

plt.figure(figsize=(15, 8))
sns.lineplot(data=df_top_countries_trend, x='year', y='cement_co2', hue='country', marker='.')
plt.title('Annual Cement CO₂ Emissions Trend for Top 10 Countries')
plt.xlabel('Year')
plt.ylabel('Cement CO₂ Emissions (million tonnes)')
plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

print("Annual cement CO₂ emissions trend for top countries data (first 5 rows):")
print(df_top_countries_trend.head())

"""### 3.4. Emission Source Contribution (Conceptual/Synthetic Data)

As direct datasets for detailed breakdowns of calcination vs. fuel combustion emissions are rare in publicly available macro-level datasets like OWID, we will use the benchmark values provided in the project context to illustrate emission source contribution. This will be a conceptual visualization based on the industry context.

**Industry Context Recall:**
- 60–70% calcination emissions
- 30–40% fuel combustion emissions

For visualization, we will use an average split: 65% calcination and 35% fuel combustion.
"""

# Using benchmark values from project context for emission source contribution
calcination_percentage = 0.65
fuel_combustion_percentage = 0.35

emission_sources = pd.DataFrame({
    'Source': ['Calcination', 'Fuel Combustion'],
    'Contribution': [calcination_percentage, fuel_combustion_percentage]
})

plt.figure(figsize=(8, 8))
plt.pie(emission_sources['Contribution'], labels=emission_sources['Source'], autopct='%1.1f%%', startangle=90, colors=['#ff9999','#66b3ff'])
plt.title('Typical Cement CO₂ Emission Source Contribution')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

print("Emission source contributions (conceptual):")
print(emission_sources)

"""### 3.5. Energy vs. Emissions Analysis (Conceptual/Synthetic Data)

Similar to emission sources, direct public datasets correlating energy intensity with cement CO₂ emissions at a global scale are not readily available. We will generate a conceptual visualization based on the provided industry benchmark values.

**Industry Context Recall:**
- Thermal energy intensity: 3.5 GJ per tonne of clinker
- Electrical intensity: 91 kWh per tonne of cement
- Clinker ratio: 0.71–0.72
- Average emission intensity: 0.54–0.55 tonnes CO₂ per tonne of cement

Let's assume an average clinker ratio of 0.72 and average emission intensity of 0.545 tonnes CO₂ per tonne of cement for calculations.
"""

# Generating synthetic data points to illustrate Energy vs Emissions
# We'll use the average values from the project context.

# Assumptions:
# - For 1 tonne of cement production:
#   - Clinker: 0.72 tonnes
#   - Cement CO2 emissions: 0.545 tonnes CO2 (average of 0.54-0.55)

# Thermal energy related to clinker production
thermal_intensity_clinker_GJ_tonne = 3.5 # GJ/tonne clinker
thermal_energy_per_tonne_cement_GJ = thermal_intensity_clinker_GJ_tonne * 0.72

# Electrical energy related to cement production
electrical_intensity_cement_kWh_tonne = 91 # kWh/tonne cement

# Convert GJ to kWh for comparison (1 GJ = 277.778 kWh)
thermal_energy_per_tonne_cement_kWh = thermal_energy_per_tonne_cement_GJ * 277.778

# Create a simple DataFrame for conceptual visualization
energy_data = pd.DataFrame({
    'Energy Type': ['Thermal Energy (from clinker)', 'Electrical Energy (for cement)'],
    'Energy Intensity (kWh/tonne cement)': [thermal_energy_per_tonne_cement_kWh, electrical_intensity_cement_kWh_tonne]
})

print("Conceptual Energy Intensities per tonne of cement:")
print(energy_data)

# Visualization: Energy Intensity
plt.figure(figsize=(10, 6))
sns.barplot(x='Energy Type', y='Energy Intensity (kWh/tonne cement)', data=energy_data, palette='coolwarm', hue='Energy Type', legend=False)
plt.title('Conceptual Energy Intensity per Tonne of Cement Production')
plt.xlabel('Energy Type')
plt.ylabel('Energy Intensity (kWh/tonne cement)')
plt.show()

# Visualization: Relationship between Emission Intensity and Energy (Conceptual)
# We'll create a hypothetical scenario to show variation
hypothetical_emission_intensity = np.array([0.50, 0.52, 0.54, 0.56, 0.58]) # tonnes CO2/tonne cement
hypothetical_thermal_energy = hypothetical_emission_intensity / 0.545 * thermal_energy_per_tonne_cement_GJ # GJ/tonne cement, scaled by emission intensity deviation
hypothetical_electrical_energy = np.full_like(hypothetical_emission_intensity, electrical_intensity_cement_kWh_tonne)

# Create a DataFrame for this conceptual relationship
df_energy_emissions_conceptual = pd.DataFrame({
    'Emission Intensity (tCO2/tCement)': hypothetical_emission_intensity,
    'Thermal Energy Intensity (GJ/tCement)': hypothetical_thermal_energy,
    'Electrical Energy Intensity (kWh/tCement)': hypothetical_electrical_energy
})

print("\nConceptual relationship between Emission Intensity and Energy (first 5 rows):")
print(df_energy_emissions_conceptual.head())

plt.figure(figsize=(12, 7))
sns.scatterplot(x='Thermal Energy Intensity (GJ/tCement)', y='Emission Intensity (tCO2/tCement)', data=df_energy_emissions_conceptual, s=100, color='red', label='Thermal Energy')
sns.scatterplot(x='Electrical Energy Intensity (kWh/tCement)', y='Emission Intensity (tCO2/tCement)', data=df_energy_emissions_conceptual, s=100, color='blue', label='Electrical Energy (scaled for visualization)')
plt.title('Conceptual: Emission Intensity vs. Energy Intensity')
plt.xlabel('Energy Intensity')
plt.ylabel('Emission Intensity (tCO₂/tCement)')
plt.legend()
plt.grid(True)
plt.show()

"""## 4. Cement Emission Calculator Class

To standardize and modularize our calculations, we will implement a Python class `CementEmissionCalculator`. This class will encapsulate the logic for calculating total emissions, process emissions (from calcination), and fuel emissions, based on activity data and emission factors derived from industry benchmarks.
"""

class CementEmissionCalculator:
    """
    A class to calculate carbon emissions from cement production.
    Uses benchmark values from industry context for emission factors and ratios.
    """

    def __init__(self, clinker_ratio=0.72, emission_factor_cement=0.545,
                 calcination_share=0.65, fuel_combustion_share=0.35,
                 thermal_intensity_clinker_GJ_tonne=3.5,
                 electrical_intensity_cement_kWh_tonne=91):
        """
        Initializes the calculator with industry benchmark values.

        Args:
            clinker_ratio (float): Ratio of clinker in cement (e.g., 0.72 for 72%).
            emission_factor_cement (float): Total CO2 emissions per tonne of cement (tCO2/tonne cement).
                                            Average of 0.54-0.55 tCO2/tonne.
            calcination_share (float): Proportion of emissions from calcination (e.g., 0.65).
            fuel_combustion_share (float): Proportion of emissions from fuel combustion (e.g., 0.35).
            thermal_intensity_clinker_GJ_tonne (float): Thermal energy intensity per tonne of clinker (GJ/tonne clinker).
            electrical_intensity_cement_kWh_tonne (float): Electrical energy intensity per tonne of cement (kWh/tonne cement).
        """
        if not (0 <= clinker_ratio <= 1): raise ValueError("Clinker ratio must be between 0 and 1.")
        if not (0 <= calcination_share <= 1) or not (0 <= fuel_combustion_share <= 1): raise ValueError("Emission shares must be between 0 and 1.")
        if abs(calcination_share + fuel_combustion_share - 1.0) > 1e-6: print("Warning: Calcination and fuel combustion shares do not sum to 1.0. Normalizing...");

        # Normalizing if not summing to 1.0
        total_share = calcination_share + fuel_combustion_share
        self.calcination_share = calcination_share / total_share
        self.fuel_combustion_share = fuel_combustion_share / total_share

        self.clinker_ratio = clinker_ratio
        self.emission_factor_cement = emission_factor_cement
        self.thermal_intensity_clinker_GJ_tonne = thermal_intensity_clinker_GJ_tonne
        self.electrical_intensity_cement_kWh_tonne = electrical_intensity_cement_kWh_tonne

        # Derived emission factors for process and fuel based on overall emission factor
        self.emission_factor_calcination = self.emission_factor_cement * self.calcination_share
        self.emission_factor_fuel = self.emission_factor_cement * self.fuel_combustion_share

        print(f"CementEmissionCalculator initialized with:" \
              f"\n  Clinker Ratio: {self.clinker_ratio}" \
              f"\n  Total Emission Factor: {self.emission_factor_cement} tCO2/tonne cement" \
              f"\n  Calcination Share: {self.calcination_share:.1%}" \
              f"\n  Fuel Combustion Share: {self.fuel_combustion_share:.1%}" \
              f"\n  Process Emission Factor: {self.emission_factor_calcination:.3f} tCO2/tonne cement" \
              f"\n  Fuel Emission Factor: {self.emission_factor_fuel:.3f} tCO2/tonne cement")

    def calculate_total_emissions(self, cement_production_tonnes):
        """
        Calculates total CO2 emissions given cement production.
        Args:
            cement_production_tonnes (float): Amount of cement produced in tonnes.
        Returns:
            float: Total CO2 emissions in tonnes.
        """
        return cement_production_tonnes * self.emission_factor_cement

    def calculate_process_emissions(self, cement_production_tonnes):
        """
        Calculates CO2 emissions from calcination given cement production.
        Args:
            cement_production_tonnes (float): Amount of cement produced in tonnes.
        Returns:
            float: Process CO2 emissions in tonnes.
        """
        return cement_production_tonnes * self.emission_factor_calcination

    def calculate_fuel_emissions(self, cement_production_tonnes):
        """
        Calculates CO2 emissions from fuel combustion given cement production.
        Args:
            cement_production_tonnes (float): Amount of cement produced in tonnes.
        Returns:
            float: Fuel CO2 emissions in tonnes.
        """
        return cement_production_tonnes * self.emission_factor_fuel

    def calculate_thermal_energy_consumption(self, cement_production_tonnes):
        """
        Calculates thermal energy consumption given cement production.
        Args:
            cement_production_tonnes (float): Amount of cement produced in tonnes.
        Returns:
            float: Thermal energy consumption in GJ.
        """
        clinker_production_tonnes = cement_production_tonnes * self.clinker_ratio
        return clinker_production_tonnes * self.thermal_intensity_clinker_GJ_tonne

    def calculate_electrical_energy_consumption(self, cement_production_tonnes):
        """
        Calculates electrical energy consumption given cement production.
        Args:
            cement_production_tonnes (float): Amount of cement produced in tonnes.
        Returns:
            float: Electrical energy consumption in kWh.
        """
        return cement_production_tonnes * self.electrical_intensity_cement_kWh_tonne

print("CementEmissionCalculator class defined.")

"""### 4.1. Applying the Calculator to Our Data

Now, let's instantiate the `CementEmissionCalculator` and apply it to a sample of our `df_cement_emissions` data to demonstrate its usage. Since the OWID dataset already provides `cement_co2`, we can use our calculator's emission factor to estimate the 'activity data' (cement production) from the reported emissions and then break down emissions based on the conceptual shares.
"""

# Initialize the calculator with default or specified benchmark values
calculator = CementEmissionCalculator()

# Let's consider a specific year and country for demonstration, e.g., China in 2020
china_2020_emissions_mt = df_cement_emissions[(df_cement_emissions['country'] == 'China') & (df_cement_emissions['year'] == 2020)]['cement_co2'].iloc[0]

# Convert million tonnes CO2 to tonnes CO2 for calculation
china_2020_emissions_tonnes = china_2020_emissions_mt * 1_000_000

# Estimate cement production from reported total emissions using the calculator's total emission factor
# This is an inverse calculation to get activity data (cement production)
cement_production_china_2020_tonnes = china_2020_emissions_tonnes / calculator.emission_factor_cement

print(f"\nEstimated Cement Production for China in 2020: {cement_production_china_2020_tonnes / 1_000_000:.2f} million tonnes")

# Calculate different types of emissions using the estimated cement production
total_emissions = calculator.calculate_total_emissions(cement_production_china_2020_tonnes)
process_emissions = calculator.calculate_process_emissions(cement_production_china_2020_tonnes)
fuel_emissions = calculator.calculate_fuel_emissions(cement_production_china_2020_tonnes)

# Calculate energy consumption
thermal_energy = calculator.calculate_thermal_energy_consumption(cement_production_china_2020_tonnes)
electrical_energy = calculator.calculate_electrical_energy_consumption(cement_production_china_2020_tonnes)

print(f"\nCalculated Emissions and Energy for China in 2020 (based on estimated production):")
print(f"  Total CO₂ Emissions: {total_emissions / 1_000_000:.2f} million tonnes")
print(f"  Process (Calcination) CO₂ Emissions: {process_emissions / 1_000_000:.2f} million tonnes")
print(f"  Fuel Combustion CO₂ Emissions: {fuel_emissions / 1_000_000:.2f} million tonnes")
print(f"  Thermal Energy Consumption: {thermal_energy / 1_000_000_000:.2f} PJ (PetaJoules)") # 1 PJ = 10^9 GJ
print(f"  Electrical Energy Consumption: {electrical_energy / 1_000_000_000:.2f} GWh (Gigawatt-hours)") # 1 GWh = 10^6 kWh

# Add these calculated values back to the DataFrame for further analysis/visualization if needed (conceptual)
# For simplicity, we'll just demonstrate the calculation here rather than modifying the main DF directly for conceptual breakdown.

"""## 5. Carbon Emission Calculations and Intensity Analysis

We will now use the `CementEmissionCalculator` to compute detailed emission breakdowns (process, fuel) and energy intensities across the entire dataset. Since the OWID dataset provides total `cement_co2` emissions, we will use our `CementEmissionCalculator`'s emission factor to *infer* the `cement_production_tonnes` from `cement_co2` and then use this inferred production to calculate process/fuel emissions and energy consumption based on the defined ratios.
"""

# Initialize the calculator (if not already done)
# This uses the default benchmark values established in the class definition
calculator = CementEmissionCalculator()

# Create new columns in the DataFrame for calculated values
# Note: cement_co2 in OWID data is already in million tonnes, our calculator expects tonnes.
# We will infer production in tonnes from OWID's million tonnes CO2.

df_cement_emissions_calculated = df_cement_emissions.copy()

# Infer cement production in tonnes from total cement_co2 (million tonnes) using the calculator's total emission factor
# Conversion: million tonnes CO2 -> tonnes CO2, then divide by emission factor to get tonnes cement
df_cement_emissions_calculated['estimated_cement_production_tonnes'] = \
    df_cement_emissions_calculated['cement_co2'] * 1_000_000 / calculator.emission_factor_cement

# Calculate Process (Calcination) Emissions (in million tonnes CO2)
df_cement_emissions_calculated['process_co2_mt'] = \
    df_cement_emissions_calculated['estimated_cement_production_tonnes'] * calculator.emission_factor_calcination / 1_000_000

# Calculate Fuel Combustion Emissions (in million tonnes CO2)
df_cement_emissions_calculated['fuel_co2_mt'] = \
    df_cement_emissions_calculated['estimated_cement_production_tonnes'] * calculator.emission_factor_fuel / 1_000_000

# Calculate Thermal Energy Consumption (in petajoules, PJ)
# Calculator returns GJ, so convert to PJ (1 PJ = 1,000 GJ)
df_cement_emissions_calculated['thermal_energy_pj'] = \
    df_cement_emissions_calculated['estimated_cement_production_tonnes'].apply(calculator.calculate_thermal_energy_consumption) / 1_000_000

# Calculate Electrical Energy Consumption (in gigawatt-hours, GWh)
# Calculator returns kWh, so convert to GWh (1 GWh = 1,000,000 kWh)
df_cement_emissions_calculated['electrical_energy_gwh'] = \
    df_cement_emissions_calculated['estimated_cement_production_tonnes'].apply(calculator.calculate_electrical_energy_consumption) / 1_000_000

print("Calculations complete. Displaying head of the new DataFrame:")
print(df_cement_emissions_calculated.head())

print("\nVerifying totals (sums should be close to original cement_co2 where data exists, adjusted for precision):")
# For a sample row, verify process + fuel == total
sample_row = df_cement_emissions_calculated.iloc[0]
print(f"Original Total CO2 (million tonnes): {sample_row['cement_co2']:.3f}")
print(f"Calculated Process CO2 (million tonnes): {sample_row['process_co2_mt']:.3f}")
print(f"Calculated Fuel CO2 (million tonnes): {sample_row['fuel_co2_mt']:.3f}")
print(f"Sum of Calculated Process + Fuel CO2 (million tonnes): {(sample_row['process_co2_mt'] + sample_row['fuel_co2_mt']):.3f}")

"""## 6. Emission Source Contribution Over Time (Data-Driven)

Now that we have computed the process and fuel emissions using our `CementEmissionCalculator`, we can visualize their contribution over time based on the actual data.
"""

# Group by year and sum up the calculated process and fuel CO2 emissions globally
global_emission_breakdown = df_cement_emissions_calculated.groupby('year')[['process_co2_mt', 'fuel_co2_mt']].sum().reset_index()

# Stacked area plot for emission breakdown
plt.figure(figsize=(14, 7))
plt.stackplot(global_emission_breakdown['year'],
              global_emission_breakdown['process_co2_mt'],
              global_emission_breakdown['fuel_co2_mt'],
              labels=['Process Emissions (Calcination)', 'Fuel Combustion Emissions'],
              colors=['#ff9999', '#66b3ff'])

plt.title('Global Cement CO₂ Emission Breakdown Over Time')
plt.xlabel('Year')
plt.ylabel('CO₂ Emissions (million tonnes)')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

print("Global emission breakdown data (first 5 rows):")
print(global_emission_breakdown.head())

"""## 7. Energy Intensity Analysis Over Time

Let's analyze the trends in thermal and electrical energy consumption over time globally.
"""

# Group by year and sum up the thermal and electrical energy consumption globally
global_energy_consumption = df_cement_emissions_calculated.groupby('year')[['thermal_energy_pj', 'electrical_energy_gwh']].sum().reset_index()

plt.figure(figsize=(14, 7))

# Thermal Energy Plot
sns.lineplot(data=global_energy_consumption, x='year', y='thermal_energy_pj', label='Thermal Energy (PJ)', marker='o', color='darkred')

# Electrical Energy Plot (using a secondary y-axis for better visualization due to different scales)
ax2 = plt.twinx()
sns.lineplot(data=global_energy_consumption, x='year', y='electrical_energy_gwh', label='Electrical Energy (GWh)', marker='x', color='darkblue', ax=ax2)

plt.title('Global Cement Production Energy Consumption Over Time')
plt.xlabel('Year')
plt.ylabel('Thermal Energy (PJ)', color='darkred')
ax2.set_ylabel('Electrical Energy (GWh)', color='darkblue')

# Combine legends
lines, labels = plt.gca().get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')

plt.grid(True)
plt.show()

print("Global energy consumption data (first 5 rows):")
print(global_energy_consumption.head())

"""## 8. Sustainability Insights

Based on the data acquisition, cleaning, emission calculations, and visualizations, we can draw several sustainability insights regarding the cement industry's carbon footprint.

### 8.1. Global Emission Trends

- **Significant Growth**: The global cement CO₂ emissions have shown a consistent upward trend over the last century, reflecting increased global demand for cement, especially with industrialization and urbanization.
- **Dominance of Calcination**: Our conceptual and data-driven breakdowns confirm that calcination is the primary source of CO₂ emissions in cement production, typically accounting for 60-70% of total emissions. This highlights the importance of clinker-substitution strategies (e.g., using supplementary cementitious materials) to reduce emissions.
- **Fuel Combustion Contribution**: While smaller than calcination, fuel combustion also contributes significantly (30-40%). Decarbonizing this aspect requires transitioning to alternative fuels (biomass, waste-derived fuels) and improving energy efficiency.

### 8.2. Country-Level Contributions

- **Concentrated Emissions**: A small number of countries, notably China and India, are major contributors to cumulative cement CO₂ emissions. This indicates that mitigation efforts in these regions could have a substantial global impact.
- **Varying Trajectories**: The annual trends for top emitters show diverse development patterns. Some established industrial nations might show stabilizing or declining trends due to mature markets and early adoption of efficiency measures, while rapidly developing economies continue to see increasing emissions.

### 8.3. Energy Intensity

- **High Energy Demand**: Cement production is an energy-intensive process, requiring significant thermal and electrical energy. Thermal energy, largely for clinker production, dominates the energy profile.
- **Opportunities for Efficiency**: Reductions in thermal and electrical energy intensities per tonne of cement can lead to lower fuel consumption and associated emissions. Innovations in kiln technology, waste heat recovery, and efficient grinding are critical.

### 8.4. Path Forward for Decarbonization

- **Material Innovation**: Reducing the clinker-to-cement ratio through the use of blended cements and novel binders is crucial for addressing calcination emissions.
- **Fuel Switching**: Shifting away from fossil fuels to alternative and renewable energy sources for kiln firing and electricity generation is vital for fuel combustion emissions.
- **Carbon Capture, Utilization, and Storage (CCUS)**: For residual emissions from calcination, CCUS technologies will play an increasingly important role.
- **Data and Transparency**: Enhanced data collection and public reporting across the industry are essential for monitoring progress and identifying further intervention points.

## 9. Steel Industry Carbon Emission Analysis

### 9.1. Our World in Data - Steel CO₂ and Greenhouse Gas Emissions

Similar to cement, 'Our World in Data' also provides comprehensive datasets on CO₂ and greenhouse gas emissions from the iron and steel industry. This will be our primary source for steel-related emissions data.
"""

import pandas as pd

# Direct URL to Our World in Data CO₂ and Greenhouse Gas Emissions dataset
# This URL might need to be updated if the source changes it.
data_url_owid_steel = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

try:
    df_owid_steel = pd.read_csv(data_url_owid_steel)
    print("Our World in Data CO₂ emissions data fetched successfully for Steel.")
    print(df_owid_steel.head())
    print(f"Shape of OWID steel data: {df_owid_steel.shape}")
except Exception as e:
    print(f"Could not fetch Our World in Data steel data. Error: {e}")
    df_owid_steel = pd.DataFrame()

"""### 9.2. Initial Data Inspection and Cleaning for OWID Steel Data

Now that we have successfully loaded the 'Our World in Data' dataset for steel, we need to inspect its structure, check for missing values, and prepare it for analysis, focusing on the `steel_co2` column.
"""

# Display basic info about the DataFrame
print("\n--- OWID Steel Data Info ---")
df_owid_steel.info()

# Check for missing values in key columns
print("\n--- Missing Values in Key Columns for Steel ---")
key_columns_steel = ['country', 'year', 'other_industry_co2', 'population', 'gdp']
for col in key_columns_steel:
    if col in df_owid_steel.columns:
        print(f"Missing values in '{col}': {df_owid_steel[col].isnull().sum()} ({(df_owid_steel[col].isnull().sum() / len(df_owid_steel)) * 100:.2f}%) ")
    else:
        print(f"Column '{col}' not found in DataFrame.")

# Filter out rows where 'other_industry_co2' is NaN or 0, as these are not useful for emission analysis
df_steel_emissions = df_owid_steel[df_owid_steel['other_industry_co2'].notna() & (df_owid_steel['other_industry_co2'] > 0)].copy()

# Focus on relevant columns for steel emissions
df_steel_emissions = df_steel_emissions[['country', 'year', 'other_industry_co2', 'population', 'gdp', 'iso_code']].copy()

print("\n--- Filtered Steel Emissions Data (first 5 rows) ---")
print(df_steel_emissions.head())
print(f"Shape of filtered steel emissions data: {df_steel_emissions.shape}")

# Further cleaning: Ensure 'year' is integer and 'other_industry_co2' is numeric
df_steel_emissions['year'] = pd.to_numeric(df_steel_emissions['year'], errors='coerce').astype(int)
df_steel_emissions['other_industry_co2'] = pd.to_numeric(df_steel_emissions['other_industry_co2'], errors='coerce')

print("\n--- Data types after cleaning for Steel ---")
print(df_steel_emissions.dtypes)

# Determine the maximum year in the dataset to calculate the start year for trimming
max_year = df_steel_emissions['year'].max()
start_year = max_year - 49 # To include the last 50 years

df_steel_emissions = df_steel_emissions[df_steel_emissions['year'] >= start_year].copy()

print(f"\nFiltered Steel Emissions Data (last 50 years, first 5 rows):")
print(df_steel_emissions.head())
print(f"Shape of filtered steel emissions data (last 50 years): {df_steel_emissions.shape}")

"""### 9.2.1. Trimming Data to Last 50 Years

To focus on more recent trends, we will now filter the `df_steel_emissions` DataFrame to include only data from the last 50 years.

### 9.3. Exploratory Data Analysis (EDA) for Steel

This section will perform exploratory data analysis on the `df_steel_emissions` dataset. We will visualize trends, distributions, and relationships to gain insights into steel-related CO₂ emissions globally and by country.

#### 9.3.1. Global Steel CO₂ Emissions Trend

Let's visualize the global trend of steel CO₂ emissions over time.
"""

# Calculate global steel CO2 emissions per year
global_steel_co2 = df_steel_emissions.groupby('year')['other_industry_co2'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=global_steel_co2, x='year', y='other_industry_co2', marker='o')
plt.title('Global Steel CO₂ Emissions Over Time (Proxy: Other Industry CO₂)')
plt.xlabel('Year')
plt.ylabel('CO₂ Emissions (million tonnes)')
plt.grid(True)
plt.show()

print("Global steel CO₂ emissions data for visualization (first 5 rows):")
print(global_steel_co2.head())

"""#### 9.3.2. Top Countries by Steel CO₂ Emissions

Let's identify the countries with the highest cumulative steel CO₂ emissions and visualize their contributions.
"""

# Filter out aggregate entities from the 'country' column to focus on individual countries
# Reusing the aggregate_entities list from cement analysis, ensure it's robust.

df_countries_only_steel = df_steel_emissions[~df_steel_emissions['country'].isin(aggregate_entities)].copy()

# Calculate cumulative steel CO2 emissions per country from the filtered data
cumulative_country_steel_co2 = df_countries_only_steel.groupby('country')['other_industry_co2'].sum().reset_index()
cumulative_country_steel_co2 = cumulative_country_steel_co2.sort_values(by='other_industry_co2', ascending=False)

# Select top N countries (e.g., top 10)
top_n = 10
top_countries_steel_co2 = cumulative_country_steel_co2.head(top_n)

plt.figure(figsize=(14, 7))
sns.barplot(x='country', y='other_industry_co2', data=top_countries_steel_co2, palette='viridis', hue='country', legend=False)
plt.title(f'Top {top_n} Countries by Cumulative Other Industry CO₂ Emissions (Proxy for Steel, 1880-2024)')
plt.xlabel('Country')
plt.ylabel('Cumulative CO₂ Emissions (million tonnes)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print(f"Top {top_n} individual countries by cumulative steel CO₂ emissions (proxy using other_industry_co2):")
print(top_countries_steel_co2)

"""#### 9.3.3. Annual Steel CO₂ Emissions Trend for Top Countries

Let's visualize the annual steel CO₂ emissions for the top countries to observe their individual trends over time.
"""

# Get the list of top N countries
top_countries_list_steel = top_countries_steel_co2['country'].tolist()

# Filter the main DataFrame to include only these top countries
df_top_countries_trend_steel = df_steel_emissions[df_steel_emissions['country'].isin(top_countries_list_steel)].copy()

plt.figure(figsize=(15, 8))
sns.lineplot(data=df_top_countries_trend_steel, x='year', y='other_industry_co2', hue='country', marker='.')
plt.title('Annual Other Industry CO₂ Emissions Trend for Top Countries (Proxy for Steel)')
plt.xlabel('Year')
plt.ylabel('CO₂ Emissions (million tonnes)')
plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

print("Annual steel CO₂ emissions trend for top countries data (proxy using other_industry_co2, first 5 rows):")
print(df_top_countries_trend_steel.head())

"""#### 9.3.4. Emission Source Contribution (Conceptual/Synthetic Data) for Steel

Similar to cement, detailed breakdowns of steel emission sources are not always readily available in macro-level datasets. We will use conceptual benchmarks for integrated steelmaking, which typically involve emissions from coke production, blast furnaces, and basic oxygen furnaces.

**Industry Context (Typical Integrated Steelmaking):**
- Emissions from direct reduction/electric arc furnaces (DRI/EAF) can differ.
- For integrated steel, typical breakdown might be:
    - Blast Furnace (Ironmaking): ~70-80%
    - Basic Oxygen Furnace (Steelmaking): ~10-15%
    - Other processes (sintering, coking, rolling, etc.): ~5-20%

For simplicity, let's use a conceptual split for total steel emissions:
- **Ironmaking (Blast Furnace/Sintering/Coking): 80%**
- **Steelmaking (Basic Oxygen Furnace): 10%**
- **Other Processes: 10%**
"""

# Using conceptual values for steel emission source contribution
ironmaking_percentage = 0.80
steelmaking_percentage = 0.10
other_processes_percentage = 0.10

emission_sources_steel = pd.DataFrame({
    'Source': ['Ironmaking (BF/Sinter)', 'Steelmaking (BOF)', 'Other Processes'],
    'Contribution': [ironmaking_percentage, steelmaking_percentage, other_processes_percentage]
})

plt.figure(figsize=(8, 8))
plt.pie(emission_sources_steel['Contribution'], labels=emission_sources_steel['Source'], autopct='%1.1f%%', startangle=90, colors=['#a1d99b','#fee090','#fdae61'])
plt.title('Typical Integrated Steel CO₂ Emission Source Contribution (Conceptual)')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

print("Steel emission source contributions (conceptual):")
print(emission_sources_steel)

"""#### 9.3.5. Energy vs. Emissions Analysis (Conceptual/Synthetic Data) for Steel

Steel production is highly energy-intensive. We'll use benchmark values to illustrate the relationship between energy consumption and emissions.

**Industry Context (Typical Integrated Steelmaking):**
- Average energy intensity: ~18-20 GJ/tonne crude steel
- Average emission intensity: ~1.8-2.0 tonnes CO₂/tonne crude steel (integrated route)

Let's assume an average energy intensity of 19 GJ/tonne and an average emission intensity of 1.9 tonnes CO₂/tonne crude steel.
"""

# Generating synthetic data points to illustrate Energy vs Emissions for Steel

# Assumptions:
# - For 1 tonne of crude steel production (integrated route):
#   - Energy intensity: 19 GJ/tonne crude steel
#   - CO2 emissions: 1.9 tonnes CO2/tonne crude steel

energy_intensity_steel_GJ_tonne = 19 # GJ/tonne crude steel
emission_intensity_steel_tco2_tonne = 1.9 # tCO2/tonne crude steel

# Create a simple DataFrame for conceptual visualization of energy intensity
energy_data_steel = pd.DataFrame({
    'Metric': ['Energy Intensity', 'Emission Intensity'],
    'Value': [energy_intensity_steel_GJ_tonne, emission_intensity_steel_tco2_tonne],
    'Unit': ['GJ/tonne steel', 'tCO2/tonne steel']
})

print("Conceptual Energy and Emission Intensities per tonne of crude steel:")
print(energy_data_steel)

# Visualization: Intensity Comparison
plt.figure(figsize=(10, 6))
sns.barplot(x='Metric', y='Value', data=energy_data_steel, hue='Metric', palette='cividis', legend=False)
plt.title('Conceptual Energy and Emission Intensities per Tonne of Crude Steel')
plt.xlabel('Metric')
plt.ylabel('Value (per tonne steel)')
plt.show()

# Visualization: Hypothetical relationship between varying energy and emission intensity
hypothetical_energy_intensity_steel = np.linspace(17, 21, 5) # GJ/tonne steel
hypothetical_emission_intensity_steel = hypothetical_energy_intensity_steel / energy_intensity_steel_GJ_tonne * emission_intensity_steel_tco2_tonne

df_energy_emissions_conceptual_steel = pd.DataFrame({
    'Energy Intensity (GJ/tSteel)': hypothetical_energy_intensity_steel,
    'Emission Intensity (tCO2/tSteel)': hypothetical_emission_intensity_steel
})

print("\nConceptual relationship between Energy Intensity and Emission Intensity for Steel (first 5 rows):")
print(df_energy_emissions_conceptual_steel.head())

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Energy Intensity (GJ/tSteel)', y='Emission Intensity (tCO2/tSteel)', data=df_energy_emissions_conceptual_steel, s=100, color='green')
plt.title('Conceptual: Emission Intensity vs. Energy Intensity for Steel')
plt.xlabel('Energy Intensity (GJ/tonne Steel)')
plt.ylabel('Emission Intensity (tCO₂/tonne Steel)')
plt.grid(True)
plt.show()

"""## 10. Steel Emission Calculator Class

To standardize and modularize our calculations for the steel industry, we will implement a Python class `SteelEmissionCalculator`. This class will encapsulate the logic for calculating total emissions and, conceptually, energy consumption, based on activity data and emission factors/intensities derived from industry benchmarks.
"""

class SteelEmissionCalculator:
    """
    A class to calculate carbon emissions from steel production.
    Uses benchmark values from industry context for emission factors and energy intensities.
    """

    def __init__(self, emission_factor_steel=1.9, # tonnes CO2/tonne crude steel (integrated)
                 ironmaking_share=0.80,
                 steelmaking_share=0.10,
                 other_processes_share=0.10,
                 energy_intensity_steel_GJ_tonne=19): # GJ/tonne crude steel
        """
        Initializes the calculator with industry benchmark values for steel.

        Args:
            emission_factor_steel (float): Total CO2 emissions per tonne of crude steel (tCO2/tonne steel).
            ironmaking_share (float): Proportion of emissions from ironmaking (e.g., 0.80).
            steelmaking_share (float): Proportion of emissions from steelmaking (e.g., 0.10).
            other_processes_share (float): Proportion of emissions from other processes (e.g., 0.10).
            energy_intensity_steel_GJ_tonne (float): Energy intensity per tonne of crude steel (GJ/tonne steel).
        """
        if not (0 <= ironmaking_share <= 1) or not (0 <= steelmaking_share <= 1) or not (0 <= other_processes_share <= 1):
            raise ValueError("Emission shares must be between 0 and 1.")
        total_share = ironmaking_share + steelmaking_share + other_processes_share
        if abs(total_share - 1.0) > 1e-6:
            print("Warning: Steel emission shares do not sum to 1.0. Normalizing...")
            self.ironmaking_share = ironmaking_share / total_share
            self.steelmaking_share = steelmaking_share / total_share
            self.other_processes_share = other_processes_share / total_share
        else:
            self.ironmaking_share = ironmaking_share
            self.steelmaking_share = steelmaking_share
            self.other_processes_share = other_processes_share

        self.emission_factor_steel = emission_factor_steel
        self.energy_intensity_steel_GJ_tonne = energy_intensity_steel_GJ_tonne

        print(f"SteelEmissionCalculator initialized with:"
              f"\n  Total Emission Factor: {self.emission_factor_steel} tCO2/tonne steel"
              f"\n  Ironmaking Share: {self.ironmaking_share:.1%}"
              f"\n  Steelmaking Share: {self.steelmaking_share:.1%}"
              f"\n  Other Processes Share: {self.other_processes_share:.1%}"
              f"\n  Energy Intensity: {self.energy_intensity_steel_GJ_tonne} GJ/tonne steel")

    def calculate_total_emissions(self, steel_production_tonnes):
        """
        Calculates total CO2 emissions given steel production.
        Args:
            steel_production_tonnes (float): Amount of crude steel produced in tonnes.
        Returns:
            float: Total CO2 emissions in tonnes.
        """
        return steel_production_tonnes * self.emission_factor_steel

    def calculate_ironmaking_emissions(self, steel_production_tonnes):
        """
        Calculates CO2 emissions from ironmaking given steel production.
        Args:
            steel_production_tonnes (float): Amount of crude steel produced in tonnes.
        Returns:
            float: Ironmaking CO2 emissions in tonnes.
        """
        return steel_production_tonnes * self.emission_factor_steel * self.ironmaking_share

    def calculate_steelmaking_emissions(self, steel_production_tonnes):
        """
        Calculates CO2 emissions from steelmaking given steel production.
        Args:
            steel_production_tonnes (float): Amount of crude steel produced in tonnes.
        Returns:
            float: Steelmaking CO2 emissions in tonnes.
        """
        return steel_production_tonnes * self.emission_factor_steel * self.steelmaking_share

    def calculate_other_process_emissions(self, steel_production_tonnes):
        """
        Calculates CO2 emissions from other processes given steel production.
        Args:
            steel_production_tonnes (float): Amount of crude steel produced in tonnes.
        Returns:
            float: Other process CO2 emissions in tonnes.
        """
        return steel_production_tonnes * self.emission_factor_steel * self.other_processes_share

    def calculate_total_energy_consumption(self, steel_production_tonnes):
        """
        Calculates total energy consumption given steel production.
        Args:
            steel_production_tonnes (float): Amount of crude steel produced in tonnes.
        Returns:
            float: Total energy consumption in GJ.
        """
        return steel_production_tonnes * self.energy_intensity_steel_GJ_tonne

print("SteelEmissionCalculator class defined.")

"""### 10.1. Applying the Calculator to Our Steel Data

Now, let's instantiate the `SteelEmissionCalculator` and apply it to a sample of our `df_steel_emissions` data to demonstrate its usage. Similar to cement, we will use the calculator's emission factor to estimate 'activity data' (crude steel production) from the reported emissions and then break down emissions and energy based on the conceptual shares and intensities.
"""

# Initialize the calculator with default or specified benchmark values for steel
steel_calculator = SteelEmissionCalculator()

# Let's consider a specific year and country for demonstration, e.g., China in 2020
# First, check if 'China' and '2020' exist in the filtered steel emissions data
if (df_steel_emissions['country'] == 'China').any() and (df_steel_emissions['year'] == 2020).any():
    china_2020_steel_emissions_mt = df_steel_emissions[(df_steel_emissions['country'] == 'China') & (df_steel_emissions['year'] == 2020)]['other_industry_co2'].iloc[0]

    # Convert million tonnes CO2 to tonnes CO2 for calculation
    china_2020_steel_emissions_tonnes = china_2020_steel_emissions_mt * 1_000_000

    # Estimate crude steel production from reported total emissions using the calculator's total emission factor
    steel_production_china_2020_tonnes = china_2020_steel_emissions_tonnes / steel_calculator.emission_factor_steel

    print(f"\nEstimated Crude Steel Production for China in 2020: {steel_production_china_2020_tonnes / 1_000_000:.2f} million tonnes")

    # Calculate different types of emissions using the estimated steel production
    total_steel_emissions = steel_calculator.calculate_total_emissions(steel_production_china_2020_tonnes)
    ironmaking_emissions = steel_calculator.calculate_ironmaking_emissions(steel_production_china_2020_tonnes)
    steelmaking_emissions = steel_calculator.calculate_steelmaking_emissions(steel_production_china_2020_tonnes)
    other_process_emissions = steel_calculator.calculate_other_process_emissions(steel_production_china_2020_tonnes)

    # Calculate total energy consumption
    total_steel_energy = steel_calculator.calculate_total_energy_consumption(steel_production_china_2020_tonnes)

    print(f"\nCalculated Emissions and Energy for China in 2020 (based on estimated production):")
    print(f"  Total CO₂ Emissions: {total_steel_emissions / 1_000_000:.2f} million tonnes")
    print(f"  Ironmaking CO₂ Emissions: {ironmaking_emissions / 1_000_000:.2f} million tonnes")
    print(f"  Steelmaking CO₂ Emissions: {steelmaking_emissions / 1_000_000:.2f} million tonnes")
    print(f"  Other Process CO₂ Emissions: {other_process_emissions / 1_000_000:.2f} million tonnes")
    print(f"  Total Energy Consumption: {total_steel_energy / 1_000_000:.2f} TJ (Terajoules)") # 1 TJ = 10^3 GJ
else:
    print("Data for China in 2020 (other_industry_co2) not found in the filtered dataset. Cannot perform demonstration.")

"""## 11. Carbon Emission Calculations and Intensity Analysis for Steel

We will now use the `SteelEmissionCalculator` to compute detailed emission breakdowns (ironmaking, steelmaking, other processes) and energy intensity across the entire steel dataset. We will infer the `steel_production_tonnes` from `steel_co2` and then use this inferred production to calculate the breakdown and energy consumption based on the defined ratios.
"""

# Initialize the calculator (if not already done)
# This uses the default benchmark values established in the class definition
steel_calculator = SteelEmissionCalculator()

# Create new columns in the DataFrame for calculated values
df_steel_emissions_calculated = df_steel_emissions.copy()

# Infer steel production in tonnes from total other_industry_co2 (million tonnes) using the calculator's total emission factor
df_steel_emissions_calculated['estimated_steel_production_tonnes'] = \
    df_steel_emissions_calculated['other_industry_co2'] * 1_000_000 / steel_calculator.emission_factor_steel

# Calculate Ironmaking Emissions (in million tonnes CO2)
df_steel_emissions_calculated['ironmaking_co2_mt'] = \
    df_steel_emissions_calculated['estimated_steel_production_tonnes'] * steel_calculator.emission_factor_steel * steel_calculator.ironmaking_share / 1_000_000

# Calculate Steelmaking Emissions (in million tonnes CO2)
df_steel_emissions_calculated['steelmaking_co2_mt'] = \
    df_steel_emissions_calculated['estimated_steel_production_tonnes'] * steel_calculator.emission_factor_steel * steel_calculator.steelmaking_share / 1_000_000

# Calculate Other Process Emissions (in million tonnes CO2)
df_steel_emissions_calculated['other_process_co2_mt'] = \
    df_steel_emissions_calculated['estimated_steel_production_tonnes'] * steel_calculator.emission_factor_steel * steel_calculator.other_processes_share / 1_000_000

# Calculate Total Energy Consumption (in terajoules, TJ)
# Calculator returns GJ, so convert to TJ (1 TJ = 1,000 GJ)
df_steel_emissions_calculated['total_energy_tj'] = \
    df_steel_emissions_calculated['estimated_steel_production_tonnes'].apply(steel_calculator.calculate_total_energy_consumption) / 1_000

print("Steel calculations complete. Displaying head of the new DataFrame:")
print(df_steel_emissions_calculated.head())

print("\nVerifying totals (sums should be close to original other_industry_co2 where data exists, adjusted for precision):")
# For a sample row, verify ironmaking + steelmaking + other == total
sample_row_steel = df_steel_emissions_calculated.iloc[0]
print(f"Original Total CO2 (million tonnes): {sample_row_steel['other_industry_co2']:.3f}")
print(f"Calculated Ironmaking CO2 (million tonnes): {sample_row_steel['ironmaking_co2_mt']:.3f}")
print(f"Calculated Steelmaking CO2 (million tonnes): {sample_row_steel['steelmaking_co2_mt']:.3f}")
print(f"Calculated Other Process CO2 (million tonnes): {sample_row_steel['other_process_co2_mt']:.3f}")
print(f"Sum of Calculated CO2 (million tonnes): {(sample_row_steel['ironmaking_co2_mt'] + sample_row_steel['steelmaking_co2_mt'] + sample_row_steel['other_process_co2_mt']):.3f}")

"""## 12. Emission Source Contribution Over Time for Steel (Data-Driven)

Now that we have computed the breakdown of steel emissions using our `SteelEmissionCalculator`, we can visualize their contribution over time based on the inferred data.
"""

# Group by year and sum up the calculated ironmaking, steelmaking, and other process CO2 emissions globally
global_steel_emission_breakdown = df_steel_emissions_calculated.groupby('year')[['ironmaking_co2_mt', 'steelmaking_co2_mt', 'other_process_co2_mt']].sum().reset_index()

# Stacked area plot for emission breakdown
plt.figure(figsize=(14, 7))
plt.stackplot(global_steel_emission_breakdown['year'],
              global_steel_emission_breakdown['ironmaking_co2_mt'],
              global_steel_emission_breakdown['steelmaking_co2_mt'],
              global_steel_emission_breakdown['other_process_co2_mt'],
              labels=['Ironmaking Emissions', 'Steelmaking Emissions', 'Other Process Emissions'],
              colors=['#a1d99b','#fee090','#fdae61'])

plt.title('Global Steel CO₂ Emission Breakdown Over Time')
plt.xlabel('Year')
plt.ylabel('CO₂ Emissions (million tonnes)')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

print("Global steel emission breakdown data (first 5 rows):")
print(global_steel_emission_breakdown.head())

"""## 13. Energy Intensity Analysis Over Time for Steel

Let's analyze the trends in total energy consumption over time globally for the steel industry.
"""

# Group by year and sum up the total energy consumption globally
global_steel_energy_consumption = df_steel_emissions_calculated.groupby('year')['total_energy_tj'].sum().reset_index()

plt.figure(figsize=(14, 7))
sns.lineplot(data=global_steel_energy_consumption, x='year', y='total_energy_tj', label='Total Energy (TJ)', marker='o', color='darkgreen')

plt.title('Global Steel Production Energy Consumption Over Time')
plt.xlabel('Year')
plt.ylabel('Total Energy (TJ)')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

print("Global steel energy consumption data (first 5 rows):")
print(global_steel_energy_consumption.head())

"""## 14. Sustainability Insights for Steel

Based on the data acquisition, cleaning, emission calculations, and visualizations for the steel industry, we can draw several sustainability insights regarding its carbon footprint.

### 14.1. Global Emission Trends

- **Significant Growth**: Similar to cement, global steel CO₂ emissions have shown a consistent upward trend, driven by industrialization and infrastructure development worldwide.
- **Dominance of Ironmaking**: Conceptual and data-driven breakdowns highlight that ironmaking, particularly the blast furnace route, is the primary source of CO₂ emissions due to the reduction of iron ore with coke. This emphasizes the need for alternative ironmaking technologies and hydrogen-based direct reduced iron (DRI).

### 14.2. Country-Level Contributions

- **Concentrated Emissions**: A few countries, often major industrial economies, dominate cumulative steel CO₂ emissions. Targeted mitigation efforts in these regions are crucial for global impact.
- **Dynamic Landscape**: The annual trends for top emitters show varying patterns, influenced by economic cycles, technological adoption, and policy changes.

### 14.3. Energy Intensity

- **High Energy Demand**: Steel production is one of the most energy-intensive industries, with significant thermal and electrical energy requirements, primarily for high-temperature processes like blast furnaces and furnaces for melting and reheating.
- **Opportunities for Efficiency**: Improving energy efficiency throughout the steelmaking process, including waste heat recovery and process optimization, can lead to substantial reductions in energy consumption and associated emissions.

### 14.4. Path Forward for Decarbonization

- **Alternative Ironmaking**: Transitioning from blast furnace-basic oxygen furnace (BF-BOF) to hydrogen-based direct reduced iron (DRI) coupled with electric arc furnaces (EAF) is a key pathway.
- **Increased Scrap Recycling**: Maximizing the use of scrap steel in EAFs significantly reduces the need for primary steel production, leading to lower energy and emissions.
- **Carbon Capture, Utilization, and Storage (CCUS)**: For processes where emissions are hard to abate, CCUS technologies are essential for capturing and storing or utilizing CO₂.
- **Energy Efficiency**: Continuous improvements in process design, heat recovery, and energy management are vital across all stages of steel production.
- **Renewable Energy Integration**: Powering EAFs and other electrical processes with renewable electricity can further reduce emissions.

## 15. Semiconductor Industry Carbon Emission Analysis

The semiconductor industry, while crucial for modern technology, is also a significant consumer of energy and contributor to greenhouse gas emissions, particularly due to its energy-intensive manufacturing processes and the use of potent process gases (e.g., PFCs). This section will analyze its carbon footprint following a similar methodology to the cement and steel industries.

### 15.1. Our World in Data - Industrial CO₂ and Greenhouse Gas Emissions (Proxy for Semiconductor)

Direct, granular data for semiconductor-specific CO₂ emissions is often proprietary or aggregated into broader industrial categories in public datasets like 'Our World in Data'. For this analysis, we will continue to use the `other_industry_co2` column as a proxy for general industrial emissions, acknowledging that this includes other sectors beyond semiconductors. If more specific data were available, a dedicated column would be preferred.
"""

import pandas as pd

# Direct URL to Our World in Data CO₂ and Greenhouse Gas Emissions dataset
data_url_owid_semiconductor = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

try:
    df_owid_semiconductor = pd.read_csv(data_url_owid_semiconductor)
    print("Our World in Data CO₂ emissions data fetched successfully for Semiconductor (using generic industrial data).")
    print(df_owid_semiconductor.head())
    print(f"Shape of OWID semiconductor data: {df_owid_semiconductor.shape}")
except Exception as e:
    print(f"Could not fetch Our World in Data semiconductor data. Error: {e}")
    df_owid_semiconductor = pd.DataFrame()

"""### 15.2. Initial Data Inspection and Cleaning for Semiconductor Data

We will inspect the `df_owid_semiconductor` DataFrame, specifically focusing on the `other_industry_co2` column as our proxy for semiconductor-related emissions. We'll filter out missing values and select relevant columns.
"""

# Display basic info about the DataFrame
print("\n--- OWID Semiconductor Data Info ---")
df_owid_semiconductor.info()

# Check for missing values in key columns
print("\n--- Missing Values in Key Columns for Semiconductor ---")
key_columns_semiconductor = ['country', 'year', 'other_industry_co2', 'population', 'gdp']
for col in key_columns_semiconductor:
    if col in df_owid_semiconductor.columns:
        print(f"Missing values in '{col}': {df_owid_semiconductor[col].isnull().sum()} ({(df_owid_semiconductor[col].isnull().sum() / len(df_owid_semiconductor)) * 100:.2f}%) ")
    else:
        print(f"Column '{col}' not found in DataFrame.")

# Filter out rows where 'other_industry_co2' is NaN or 0
df_semiconductor_emissions = df_owid_semiconductor[df_owid_semiconductor['other_industry_co2'].notna() & (df_owid_semiconductor['other_industry_co2'] > 0)].copy()

# Focus on relevant columns for semiconductor (using other_industry_co2 as proxy)
df_semiconductor_emissions = df_semiconductor_emissions[['country', 'year', 'other_industry_co2', 'population', 'gdp', 'iso_code']].copy()

print("\n--- Filtered Semiconductor Emissions Data (first 5 rows) ---")
print(df_semiconductor_emissions.head())
print(f"Shape of filtered semiconductor emissions data: {df_semiconductor_emissions.shape}")

# Ensure 'year' is integer and 'other_industry_co2' is numeric
df_semiconductor_emissions['year'] = pd.to_numeric(df_semiconductor_emissions['year'], errors='coerce').astype(int)
df_semiconductor_emissions['other_industry_co2'] = pd.to_numeric(df_semiconductor_emissions['other_industry_co2'], errors='coerce')

print("\n--- Data types after cleaning for Semiconductor ---")
print(df_semiconductor_emissions.dtypes)

"""### 15.2.1. Trimming Data to Last 50 Years

To focus on more recent trends, we will now filter the `df_semiconductor_emissions` DataFrame to include only data from the last 50 years, aligning with the approach for steel.
"""

# Determine the maximum year in the dataset to calculate the start year for trimming
max_year_semiconductor = df_semiconductor_emissions['year'].max()
start_year_semiconductor = max_year_semiconductor - 49 # To include the last 50 years

df_semiconductor_emissions = df_semiconductor_emissions[df_semiconductor_emissions['year'] >= start_year_semiconductor].copy()

print(f"\nFiltered Semiconductor Emissions Data (last 50 years, first 5 rows):")
print(df_semiconductor_emissions.head())
print(f"Shape of filtered semiconductor emissions data (last 50 years): {df_semiconductor_emissions.shape}")

"""### 15.3. Exploratory Data Analysis (EDA) for Semiconductor

This section will perform exploratory data analysis on the `df_semiconductor_emissions` dataset. We will visualize trends and distributions to gain insights into general industrial CO₂ emissions, serving as a proxy for the semiconductor industry.

#### 15.3.1. Global Industrial CO₂ Emissions Trend (Proxy for Semiconductor)
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate global industrial CO2 emissions per year
global_semiconductor_co2 = df_semiconductor_emissions.groupby('year')['other_industry_co2'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=global_semiconductor_co2, x='year', y='other_industry_co2', marker='o')
plt.title('Global Industrial CO₂ Emissions Over Time (Proxy for Semiconductor)')
plt.xlabel('Year')
plt.ylabel('CO₂ Emissions (million tonnes)')
plt.grid(True)
plt.show()

print("Global industrial CO₂ emissions data for visualization (first 5 rows):")
print(global_semiconductor_co2.head())

"""#### 15.3.2. Top Countries by Industrial CO₂ Emissions (Proxy for Semiconductor)

Let's identify the countries with the highest cumulative industrial CO₂ emissions (as a proxy for semiconductor-related emissions) and visualize their contributions.
"""

# Filter out aggregate entities from the 'country' column to focus on individual countries
# Reusing the aggregate_entities list from cement analysis, ensure it's robust.
aggregate_entities = [
    'World', 'Asia', 'Europe', 'Africa', 'North America', 'South America', 'Oceania',
    'European Union (27)', 'European Union (28)', 'Upper-middle-income countries',
    'High-income countries', 'Lower-middle-income countries', 'Low-income countries',
    'High income', 'Low income', 'Upper middle income', 'Lower middle income',
    'European Union', 'OECD', 'Non-OECD', 'International transport', 'Kuwaiti Oil Fires',
    'Asia (excl. China and India)', 'Europe (excl. EU-27)', 'Europe (excl. EU-28)', 'North America (excl. USA)',
    'Africa (excl. South Africa)', 'Oceania (excl. Australia and New Zealand)', 'South America (excl. Brazil)' # Further expanded
]
df_countries_only_semiconductor = df_semiconductor_emissions[~df_semiconductor_emissions['country'].isin(aggregate_entities)].copy()

# Calculate cumulative industrial CO2 emissions per country from the filtered data
cumulative_country_semiconductor_co2 = df_countries_only_semiconductor.groupby('country')['other_industry_co2'].sum().reset_index()
cumulative_country_semiconductor_co2 = cumulative_country_semiconductor_co2.sort_values(by='other_industry_co2', ascending=False)

# Select top N countries (e.g., top 10)
top_n_semiconductor = 10
top_countries_semiconductor_co2 = cumulative_country_semiconductor_co2.head(top_n_semiconductor)

plt.figure(figsize=(14, 7))
sns.barplot(x='country', y='other_industry_co2', data=top_countries_semiconductor_co2, palette='magma', hue='country', legend=False)
plt.title(f'Top {top_n_semiconductor} Countries by Cumulative Industrial CO₂ Emissions (Proxy for Semiconductor)')
plt.xlabel('Country')
plt.ylabel('Cumulative CO₂ Emissions (million tonnes)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print(f"Top {top_n_semiconductor} individual countries by cumulative industrial CO₂ emissions (proxy for semiconductor):")
print(top_countries_semiconductor_co2)

"""#### 15.3.3. Annual Industrial CO₂ Emissions Trend for Top Countries (Proxy for Semiconductor)

Let's visualize the annual industrial CO₂ emissions for the top countries to observe their individual trends over time.
"""

# Select top N countries (e.g., top 10)
top_n_semiconductor = 10
top_countries_semiconductor_co2 = cumulative_country_semiconductor_co2.head(top_n_semiconductor)

# Get the list of top N countries
top_countries_list_semiconductor = top_countries_semiconductor_co2['country'].tolist()

# Filter the main DataFrame to include only these top countries
df_top_countries_trend_semiconductor = df_semiconductor_emissions[df_semiconductor_emissions['country'].isin(top_countries_list_semiconductor)].copy()

plt.figure(figsize=(15, 8))
sns.lineplot(data=df_top_countries_trend_semiconductor, x='year', y='other_industry_co2', hue='country', marker='.')
plt.title('Annual Industrial CO₂ Emissions Trend for Top Countries (Proxy for Semiconductor)')
plt.xlabel('Year')
plt.ylabel('CO₂ Emissions (million tonnes)')
plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

print("Annual industrial CO₂ emissions trend for top countries data (proxy for semiconductor, first 5 rows):")
print(df_top_countries_trend_semiconductor.head())

"""#### 15.3.4. Emission Source Contribution (Conceptual/Synthetic Data) for Semiconductor

The semiconductor industry's emissions profile is complex, involving direct emissions from highly potent process gases (PFCs, NF3, SF6, etc.), and indirect emissions from massive electricity consumption. Direct, granular public data for these breakdowns is scarce. We will use conceptual benchmarks to illustrate typical contributions.

**Industry Context (Typical Semiconductor Manufacturing):**
- **Indirect Emissions (Electricity)**: Significant, due to energy-intensive processes like cleanrooms, lithography, etching, and heating/cooling.
- **Direct Emissions (Process Gases)**: High Global Warming Potential (GWP) gases used in etching, cleaning, and deposition. Examples include perfluorocarbons (PFCs), sulfur hexafluoride (SF6), and nitrogen trifluoride (NF3).
- **Direct Emissions (Fuel Combustion)**: From on-site power generation or heating, typically a smaller share compared to electricity or process gases.

For a conceptual split, we can assume:
- **Indirect Emissions (Electricity): 70%** (dominant due to high energy demand)
- **Direct Emissions (Process Gases): 20%** (critical due to high GWP)
- **Direct Emissions (Fuel Combustion): 10%**
"""

# Using conceptual values for semiconductor emission source contribution
indirect_electricity_percentage = 0.70
direct_process_gases_percentage = 0.20
direct_fuel_combustion_percentage = 0.10

emission_sources_semiconductor = pd.DataFrame({
    'Source': ['Indirect Emissions (Electricity)', 'Direct Emissions (Process Gases)', 'Direct Emissions (Fuel Combustion)'],
    'Contribution': [indirect_electricity_percentage, direct_process_gases_percentage, direct_fuel_combustion_percentage]
})

plt.figure(figsize=(8, 8))
plt.pie(emission_sources_semiconductor['Contribution'], labels=emission_sources_semiconductor['Source'], autopct='%1.1f%%', startangle=90, colors=['#a6cee3','#1f78b4','#b2df8a'])
plt.title('Typical Semiconductor CO₂e Emission Source Contribution (Conceptual)')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

print("Semiconductor emission source contributions (conceptual):")
print(emission_sources_semiconductor)

"""#### 15.3.5. Energy vs. Emissions Analysis (Conceptual/Synthetic Data) for Semiconductor

Semiconductor manufacturing is one of the most energy-intensive industries. While precise energy and emission intensities vary significantly based on process nodes, fab size, and product type, we can use conceptual values to illustrate the relationship.

**Industry Context (Conceptual):**
- Energy intensity: High, largely electrical.
- Emission intensity: Driven by electricity generation mix and process gas management.

Let's assume a conceptual average emission intensity of 0.8-1.2 tonnes CO₂e per million USD revenue or per kg of silicon processed (for simplicity, we'll relate it to a hypothetical 'production unit').

For this exercise, we will assume a high correlation between energy consumption and emissions, and represent a conceptual 'energy intensity' (e.g., kWh per production unit) and 'emission intensity' (tCO2e per production unit).
"""

import numpy as np

# Generating synthetic data points to illustrate Energy vs Emissions for Semiconductor

# Assumptions:
# - Conceptual 'production unit' for semiconductor (e.g., equivalent to a certain number of wafers)
# - High electrical energy intensity
# - Emissions primarily from electricity and process gases

conceptual_energy_intensity_kWh_unit = 50000 # kWh per conceptual production unit
conceptual_emission_intensity_tco2e_unit = 25 # tCO2e per conceptual production unit

# Create a simple DataFrame for conceptual visualization of intensity
intensity_data_semiconductor = pd.DataFrame({
    'Metric': ['Energy Intensity', 'Emission Intensity'],
    'Value': [conceptual_energy_intensity_kWh_unit, conceptual_emission_intensity_tco2e_unit],
    'Unit': ['kWh/unit', 'tCO2e/unit']
})

print("Conceptual Energy and Emission Intensities per Semiconductor Production Unit:")
print(intensity_data_semiconductor)

# Visualization: Intensity Comparison
plt.figure(figsize=(10, 6))
sns.barplot(x='Metric', y='Value', data=intensity_data_semiconductor, hue='Metric', palette='cividis', legend=False)
plt.title('Conceptual Energy and CO₂e Intensities per Semiconductor Production Unit')
plt.xlabel('Metric')
plt.ylabel('Value (per Production Unit)')
plt.show()

# Visualization: Hypothetical relationship between varying energy and emission intensity
hypothetical_energy_intensity_semiconductor = np.linspace(40000, 60000, 5) # kWh/unit
hypothetical_emission_intensity_semiconductor = hypothetical_energy_intensity_semiconductor / conceptual_energy_intensity_kWh_unit * conceptual_emission_intensity_tco2e_unit

df_energy_emissions_conceptual_semiconductor = pd.DataFrame({
    'Energy Intensity (kWh/unit)': hypothetical_energy_intensity_semiconductor,
    'Emission Intensity (tCO2e/unit)': hypothetical_emission_intensity_semiconductor
})

print("\nConceptual relationship between Energy Intensity and Emission Intensity for Semiconductor (first 5 rows):")
print(df_energy_emissions_conceptual_semiconductor.head())

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Energy Intensity (kWh/unit)', y='Emission Intensity (tCO2e/unit)', data=df_energy_emissions_conceptual_semiconductor, s=100, color='purple')
plt.title('Conceptual: Emission Intensity vs. Energy Intensity for Semiconductor')
plt.xlabel('Energy Intensity (kWh/Production Unit)')
plt.ylabel('Emission Intensity (tCO₂e/Production Unit)')
plt.grid(True)
plt.show()

"""## 16. Semiconductor Emission Calculator Class

To standardize and modularize our calculations for the semiconductor industry, we will implement a Python class `SemiconductorEmissionCalculator`. This class will encapsulate the logic for calculating total emissions, and breaking them down conceptually into indirect (electricity), direct (process gases), and direct (fuel combustion) based on activity data and emission factors/intensities derived from industry benchmarks.
"""

class SemiconductorEmissionCalculator:
    """
    A class to calculate carbon emissions from semiconductor manufacturing.
    Uses benchmark values from industry context for emission factors and energy intensities.
    """

    def __init__(self, emission_factor_total=0.5, # Conceptual tCO2e per 'production unit' (e.g., per MUSD revenue or per kg silicon)
                 indirect_electricity_share=0.70,
                 direct_process_gases_share=0.20,
                 direct_fuel_combustion_share=0.10,
                 electrical_intensity_kwh_unit=50000): # Conceptual kWh per 'production unit'
        """
        Initializes the calculator with industry benchmark values for semiconductor.

        Args:
            emission_factor_total (float): Total CO2e emissions per conceptual 'production unit'.
            indirect_electricity_share (float): Proportion of emissions from indirect electricity consumption.
            direct_process_gases_share (float): Proportion of emissions from direct process gases.
            direct_fuel_combustion_share (float): Proportion of emissions from direct fuel combustion.
            electrical_intensity_kwh_unit (float): Electrical energy intensity per conceptual 'production unit' (kWh/unit).
        """
        if not (0 <= indirect_electricity_share <= 1) or \
           not (0 <= direct_process_gases_share <= 1) or \
           not (0 <= direct_fuel_combustion_share <= 1):
            raise ValueError("Emission shares must be between 0 and 1.")

        total_share = indirect_electricity_share + direct_process_gases_share + direct_fuel_combustion_share
        if abs(total_share - 1.0) > 1e-6:
            print("Warning: Semiconductor emission shares do not sum to 1.0. Normalizing...")
            self.indirect_electricity_share = indirect_electricity_share / total_share
            self.direct_process_gases_share = direct_process_gases_share / total_share
            self.direct_fuel_combustion_share = direct_fuel_combustion_share / total_share
        else:
            self.indirect_electricity_share = indirect_electricity_share
            self.direct_process_gases_share = direct_process_gases_share
            self.direct_fuel_combustion_share = direct_fuel_combustion_share

        self.emission_factor_total = emission_factor_total
        self.electrical_intensity_kwh_unit = electrical_intensity_kwh_unit

        print(f"SemiconductorEmissionCalculator initialized with:"
              f"\n  Total Emission Factor: {self.emission_factor_total} tCO2e/production unit"
              f"\n  Indirect Electricity Share: {self.indirect_electricity_share:.1%}"
              f"\n  Direct Process Gases Share: {self.direct_process_gases_share:.1%}"
              f"\n  Direct Fuel Combustion Share: {self.direct_fuel_combustion_share:.1%}"
              f"\n  Electrical Intensity: {self.electrical_intensity_kwh_unit} kWh/production unit")

    def calculate_total_emissions(self, production_units):
        """
        Calculates total CO2e emissions given a number of production units.
        Args:
            production_units (float): Number of conceptual production units.
        Returns:
            float: Total CO2e emissions in tonnes.
        """
        return production_units * self.emission_factor_total

    def calculate_indirect_electricity_emissions(self, production_units):
        """
        Calculates indirect CO2e emissions from electricity given production units.
        Args:
            production_units (float): Number of conceptual production units.
        Returns:
            float: Indirect CO2e emissions in tonnes.
        """
        return production_units * self.emission_factor_total * self.indirect_electricity_share

    def calculate_direct_process_gases_emissions(self, production_units):
        """
        Calculates direct CO2e emissions from process gases given production units.
        Args:
            production_units (float): Number of conceptual production units.
        Returns:
            float: Direct CO2e emissions in tonnes.
        """
        return production_units * self.emission_factor_total * self.direct_process_gases_share

    def calculate_direct_fuel_combustion_emissions(self, production_units):
        """
        Calculates direct CO2e emissions from fuel combustion given production units.
        Args:
            production_units (float): Number of conceptual production units.
        Returns:
            float: Direct CO2e emissions in tonnes.
        """
        return production_units * self.emission_factor_total * self.direct_fuel_combustion_share

    def calculate_electrical_energy_consumption(self, production_units):
        """
        Calculates total electrical energy consumption given production units.
        Args:
            production_units (float): Number of conceptual production units.
        Returns:
            float: Electrical energy consumption in kWh.
        """
        return production_units * self.electrical_intensity_kwh_unit

print("SemiconductorEmissionCalculator class defined.")

"""### 16.1. Applying the Calculator to Our Semiconductor Data

Now, let's instantiate the `SemiconductorEmissionCalculator` and apply it to a sample of our `df_semiconductor_emissions` data. Since the OWID dataset provides `other_industry_co2` emissions (our proxy), we will use our calculator's total emission factor to *infer* the 'activity data' (conceptual 'production units') from the reported emissions and then break down emissions and energy based on the conceptual shares and intensities.
"""

# Initialize the calculator with default or specified benchmark values for semiconductor
semiconductor_calculator = SemiconductorEmissionCalculator(emission_factor_total=1.0) # Using 1.0 tCO2e/million tonnes for simplicity of inversion

# Let's consider a specific year and country for demonstration, e.g., China in 2020
# First, check if 'China' and '2020' exist in the filtered semiconductor emissions data
if ('China' in df_semiconductor_emissions['country'].unique()) and (2020 in df_semiconductor_emissions['year'].unique()):
    china_2020_semiconductor_emissions_mt = df_semiconductor_emissions[(df_semiconductor_emissions['country'] == 'China') & (df_semiconductor_emissions['year'] == 2020)]['other_industry_co2'].iloc[0]

    # Convert million tonnes CO2 to tonnes CO2e for calculation (assuming 1 Mt CO2 = 1 Mt CO2e for this proxy)
    china_2020_semiconductor_emissions_tonnes = china_2020_semiconductor_emissions_mt * 1_000_000

    # Estimate conceptual 'production units' from reported total emissions using the calculator's total emission factor
    # Using an emission_factor_total of 1.0 makes the 'production units' numerically equal to total emissions in tonnes for this proxy
    semiconductor_production_units_china_2020 = china_2020_semiconductor_emissions_tonnes / semiconductor_calculator.emission_factor_total

    print(f"\nEstimated Conceptual Semiconductor Production Units for China in 2020: {semiconductor_production_units_china_2020 / 1_000_000:.2f} million units (proxy)")

    # Calculate different types of emissions using the estimated production units
    total_semiconductor_emissions = semiconductor_calculator.calculate_total_emissions(semiconductor_production_units_china_2020)
    indirect_electricity_emissions = semiconductor_calculator.calculate_indirect_electricity_emissions(semiconductor_production_units_china_2020)
    direct_process_gases_emissions = semiconductor_calculator.calculate_direct_process_gases_emissions(semiconductor_production_units_china_2020)
    direct_fuel_combustion_emissions = semiconductor_calculator.calculate_direct_fuel_combustion_emissions(semiconductor_production_units_china_2020)

    # Calculate electrical energy consumption
    electrical_energy_consumption_semiconductor = semiconductor_calculator.calculate_electrical_energy_consumption(semiconductor_production_units_china_2020)

    print(f"\nCalculated Emissions and Energy for China in 2020 (based on estimated production units):")
    print(f"  Total CO₂e Emissions: {total_semiconductor_emissions / 1_000_000:.2f} million tonnes CO₂e")
    print(f"  Indirect (Electricity) CO₂e Emissions: {indirect_electricity_emissions / 1_000_000:.2f} million tonnes CO₂e")
    print(f"  Direct (Process Gases) CO₂e Emissions: {direct_process_gases_emissions / 1_000_000:.2f} million tonnes CO₂e")
    print(f"  Direct (Fuel Combustion) CO₂e Emissions: {direct_fuel_combustion_emissions / 1_000_000:.2f} million tonnes CO₂e")
    print(f"  Electrical Energy Consumption: {electrical_energy_consumption_semiconductor / 1_000_000_000:.2f} TWh (Terawatt-hours)") # 1 TWh = 10^9 kWh
else:
    print("Data for China in 2020 (other_industry_co2) not found in the filtered dataset. Cannot perform demonstration.")

"""## 17. Carbon Emission Calculations and Intensity Analysis for Semiconductor

We will now use the `SemiconductorEmissionCalculator` to compute detailed emission breakdowns (indirect electricity, direct process gases, direct fuel combustion) and electrical energy consumption across the entire semiconductor (proxy) dataset. We will infer the conceptual 'production units' from `other_industry_co2` and then use this inferred activity to calculate the breakdown and energy consumption based on the defined ratios.
"""

# Initialize the calculator (if not already done)
# Using a total emission factor of 1.0 makes the inferred 'production units' numerically equal to the CO2 emissions in tonnes.
# This simplifies the proxy scenario where 'other_industry_co2' directly represents the total emissions from the proxy sector.
semiconductor_calculator = SemiconductorEmissionCalculator(emission_factor_total=1.0)

# Create new columns in the DataFrame for calculated values
df_semiconductor_emissions_calculated = df_semiconductor_emissions.copy()

# Infer conceptual 'production units' from total other_industry_co2 (million tonnes) using the calculator's total emission factor
df_semiconductor_emissions_calculated['estimated_production_units'] = \
    df_semiconductor_emissions_calculated['other_industry_co2'] * 1_000_000 / semiconductor_calculator.emission_factor_total

# Calculate Indirect (Electricity) Emissions (in million tonnes CO2e)
df_semiconductor_emissions_calculated['indirect_electricity_co2e_mt'] = \
    df_semiconductor_emissions_calculated['estimated_production_units'] * semiconductor_calculator.emission_factor_total * semiconductor_calculator.indirect_electricity_share / 1_000_000

# Calculate Direct (Process Gases) Emissions (in million tonnes CO2e)
df_semiconductor_emissions_calculated['direct_process_gases_co2e_mt'] = \
    df_semiconductor_emissions_calculated['estimated_production_units'] * semiconductor_calculator.emission_factor_total * semiconductor_calculator.direct_process_gases_share / 1_000_000

# Calculate Direct (Fuel Combustion) Emissions (in million tonnes CO2e)
df_semiconductor_emissions_calculated['direct_fuel_combustion_co2e_mt'] = \
    df_semiconductor_emissions_calculated['estimated_production_units'] * semiconductor_calculator.emission_factor_total * semiconductor_calculator.direct_fuel_combustion_share / 1_000_000

# Calculate Total Electrical Energy Consumption (in Terawatt-hours, TWh)
# Calculator returns kWh, so convert to TWh (1 TWh = 1,000,000,000 kWh)
df_semiconductor_emissions_calculated['electrical_energy_twh'] = \
    df_semiconductor_emissions_calculated['estimated_production_units'].apply(semiconductor_calculator.calculate_electrical_energy_consumption) / 1_000_000_000

print("Semiconductor calculations complete. Displaying head of the new DataFrame:")
print(df_semiconductor_emissions_calculated.head())

print("\nVerifying totals (sums should be close to original other_industry_co2 where data exists, adjusted for precision):")
# For a sample row, verify indirect_electricity + direct_process_gases + direct_fuel_combustion == total
sample_row_semiconductor = df_semiconductor_emissions_calculated.iloc[0]
print(f"Original Total CO2 (million tonnes): {sample_row_semiconductor['other_industry_co2']:.3f}")
print(f"Calculated Indirect Electricity CO2e (million tonnes): {sample_row_semiconductor['indirect_electricity_co2e_mt']:.3f}")
print(f"Calculated Direct Process Gases CO2e (million tonnes): {sample_row_semiconductor['direct_process_gases_co2e_mt']:.3f}")
print(f"Calculated Direct Fuel Combustion CO2e (million tonnes): {sample_row_semiconductor['direct_fuel_combustion_co2e_mt']:.3f}")
print(f"Sum of Calculated CO2e (million tonnes): {(sample_row_semiconductor['indirect_electricity_co2e_mt'] + sample_row_semiconductor['direct_process_gases_co2e_mt'] + sample_row_semiconductor['direct_fuel_combustion_co2e_mt']):.3f}")

"""## 18. Emission Source Contribution Over Time for Semiconductor (Data-Driven)

Now that we have computed the breakdown of semiconductor emissions using our `SemiconductorEmissionCalculator`, we can visualize their contribution over time based on the inferred data.
"""

# Group by year and sum up the calculated emission categories globally
global_semiconductor_emission_breakdown = df_semiconductor_emissions_calculated.groupby('year')[['indirect_electricity_co2e_mt', 'direct_process_gases_co2e_mt', 'direct_fuel_combustion_co2e_mt']].sum().reset_index()

# Stacked area plot for emission breakdown
plt.figure(figsize=(14, 7))
plt.stackplot(global_semiconductor_emission_breakdown['year'],
              global_semiconductor_emission_breakdown['indirect_electricity_co2e_mt'],
              global_semiconductor_emission_breakdown['direct_process_gases_co2e_mt'],
              global_semiconductor_emission_breakdown['direct_fuel_combustion_co2e_mt'],
              labels=['Indirect Emissions (Electricity)', 'Direct Emissions (Process Gases)', 'Direct Emissions (Fuel Combustion)'],
              colors=['#a6cee3','#1f78b4','#b2df8a'])

plt.title('Global Industrial CO₂e Emission Breakdown Over Time (Proxy for Semiconductor)')
plt.xlabel('Year')
plt.ylabel('CO₂e Emissions (million tonnes)')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

print("Global semiconductor emission breakdown data (first 5 rows):")
print(global_semiconductor_emission_breakdown.head())

"""## 19. Energy Intensity Analysis Over Time for Semiconductor

Let's analyze the trends in total electrical energy consumption over time globally for the semiconductor (proxy) industry.
"""

# Group by year and sum up the total electrical energy consumption globally
global_semiconductor_energy_consumption = df_semiconductor_emissions_calculated.groupby('year')['electrical_energy_twh'].sum().reset_index()

plt.figure(figsize=(14, 7))
sns.lineplot(data=global_semiconductor_energy_consumption, x='year', y='electrical_energy_twh', label='Electrical Energy (TWh)', marker='o', color='darkblue')

plt.title('Global Industrial Electrical Energy Consumption Over Time (Proxy for Semiconductor)')
plt.xlabel('Year')
plt.ylabel('Electrical Energy (TWh)')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

print("Global semiconductor electrical energy consumption data (first 5 rows):")
print(global_semiconductor_energy_consumption.head())

"""## 20. Sustainability Insights for Semiconductor

Based on the conceptual analysis of the semiconductor industry (using `other_industry_co2` as a proxy), we can draw several sustainability insights regarding its carbon footprint.

### 20.1. Global Emission Trends (Proxy)

- **Growth in Industrial Emissions**: The 'other industry' CO₂ emissions, which serve as our proxy, generally show an increasing trend, reflecting global industrial expansion. While not specific to semiconductors, this broadly suggests increasing environmental impact from high-tech manufacturing sectors.
- **Dominance of Indirect Emissions**: Our conceptual breakdown indicates that indirect emissions from electricity consumption are the largest contributor. This underscores the critical importance of decarbonizing electricity grids to reduce the semiconductor industry's footprint.
- **Potency of Process Gases**: Although direct emissions from process gases might be a smaller *volume* compared to CO₂ from electricity, their high Global Warming Potential (GWP) makes them a significant concern. Mitigation efforts for these gases are crucial.

### 20.2. Country-Level Contributions (Proxy)

- **Concentrated Industrial Hubs**: The top countries in the 'other industry' category likely correlate with major industrial and technological manufacturing hubs, many of which host significant semiconductor production. Targeted efforts in these regions could yield substantial results.
- **Role of Policy and Clean Energy**: Countries with strong policies promoting renewable energy and stricter environmental regulations may see a slower growth or even a reduction in the indirect emissions from their semiconductor sector, despite production growth.

### 20.3. Energy Intensity

- **Extremely High Energy Demand**: Semiconductor manufacturing is inherently energy-intensive. Facilities require vast amounts of electricity for fabrication processes, ultra-clean environments (HVAC), and specialized equipment.
- **Efficiency Opportunities**: Continuous innovation in energy-efficient equipment, optimized process flows, and advanced building management systems are essential to reduce the substantial electrical energy footprint.

### 20.4. Path Forward for Decarbonization

- **Renewable Energy Procurement**: Shifting to 100% renewable electricity sources (e.g., solar, wind) through direct purchases, power purchase agreements, or on-site generation is paramount to address indirect emissions.
- **Process Gas Abatement**: Implementing and optimizing abatement technologies for high GWP process gases (PFCs, SF6, NF3) to destroy or capture them before release.
- **Material Substitution**: Research and development into less environmentally harmful process gases or alternative manufacturing methods.
- **Energy Efficiency**: Investing in energy-efficient fab design, advanced cooling systems, and optimizing manufacturing processes to reduce overall energy consumption.
- **Supply Chain Engagement**: Working with suppliers to ensure sustainable practices and lower embodied emissions in materials and components.
- **Water Conservation**: While not a direct carbon emission, water usage in semiconductor manufacturing is also significant, and efforts to reduce and recycle water can indirectly impact energy use and sustainability.
"""